status = WARN

#Console level output
appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %5p [%t] %c{2}: %m%n

rootLogger.level = WARN
rootLogger.appenderRef.stdout.ref = console

logger.tez.name = org.apache.tez
logger.tez.level = DEBUG
logger.tez.appenderRef.console.ref = console

logger.ipc.name = org.apache.hadoop.ipc
logger.ipc.level = INFO
logger.ipc.appenderRef.console.ref = console